Class {
	#name : #MatchCVAClass,
	#superclass : #MatchClass,
	#category : #'LanguageMetamodels-MatchCVAspects'
}

{ #category : #binding }
MatchCVAClass >> bindingOf: aSymbol [ 
	^ nil
]

{ #category : #binding }
MatchCVAClass >> innerBindingOf: aSymbol [ 
	^ nil
]

{ #category : #binding }
MatchCVAClass >> installCustom [
	super installCustom
]

{ #category : #binding }
MatchCVAClass >> transform [ 
	
]
